### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by dobaybalazs** [Teaching-projects/-SZE-MOSZE-2020-CADbol-ny--CLOSED#22]
Elkészítettük a feladatokat @hegyhati . A videók mérete miatt nem tudtuk feltölteni őket a repoba(>100MB), úgyhogy ha nem probléma drive linkeket tettünk hivatkozásnak, ahonnan elérhetőek.

**Comment by hegyhati** [comment]
de, problema. rendereljetek ujra, vajtatok ket darabba, vagy valami. Aztan assignoljatok.

**Comment by Medivessing** [comment]
@hegyhati Mp4 formátum mennyire kötött?

**Comment by hegyhati** [comment]
Hat az mp4 igazabol csak egy container, azon sok nem mulik szerintem, a meretet inkabb a felbontas, kodolas befolyasolja. De nem ertem, mi a problema egy 2 perces videon. Itt van pl az utolso OO video, ami 32 perc fullHD-ban, 30 fps, es 109 mega.
![image](https://user-images.githubusercontent.com/13832329/101691242-b573a280-3a6e-11eb-93f9-e4fcb22f2eba.png)

**Comment by dobaybalazs** [comment]
Bekerültek a videók @hegyhati  .

**Comment by vizvezetek** [comment]
A féléves feladatnak megfelelően a megajánlott érdemjegyek  a következő szerint alakultak:
- @tupoljev  : 4
- @dobaybalazs  : 5
- @Medivessing  : 3
