### ISSUE TITLE
Github pages beállítani

### ISSUE THREAD

**Issue by tupoljev** [Teaching-projects/-SZE-MOSZE-2020-CADbol-ny--CLOSED#5]
@hegyhati Kérlek állítsd be a gh-pages branchet, root-ra.

**Comment by hegyhati** [comment]
-.-
![image](https://user-images.githubusercontent.com/13832329/96160906-e3c57d80-0f16-11eb-9dbb-ffd35e026ae0.png)

**Comment by tupoljev** [comment]
Akkor ha jól értelmezem a gh-pages branchet külön pr-ral kell megnyitni? Mert a forkolt repomban rendesen lefutott a gha action a doxygen dokumentáció generáláshoz, és létrejött a gp-pages branch. Előre is köszi a választ @hegyhati.

**Comment by hegyhati** [comment]
branchet nem lehet PR-tal megnyitni. 
Azt pedig, hgoy leforkoltad a repot, meg sem hallottam :-) Nem mutatoba csinaljuk ezeket a repokat, hanem hogy ezeken dolgozzatok :-)

**Comment by tupoljev** [comment]
@hegyhati  Hibák orvosolva!

**Comment by hegyhati** [comment]
hostolas beallitva :-)
